######################################################################
# $Id: Makefile,v 1.6 2002/05/13 23:21:29 jtt Exp $
#
# ++Copyright BAKA++
#
# Copyright (c) 2001-2010 The Authors. All rights reserved.
#
# This source code is licensed to you under the terms of the file
# LICENSE.TXT in this release for further details.
#
# Send e-mail to <projectbaka@baka.org> for further information.
#
# - -Copyright BAKA- -
#
# libbk Makefile
#
BK_LARGE_LIB=../libfsma$(LIBEXT)
BK_LARGE_LIBSRC=fsma.c
BK_MAN=fsma.3


GROUPTOP=../..
GROUPSUBDIR=src/fsma
##################################################
## BEGIN BKSTANDARD MAKEFILE
-include ./Make.preinclude
-include $(GROUPTOP)/Make.preinclude
-include $(GROUPTOP)/$(PKGTOP)/Make.preinclude
include $(GROUPTOP)/$(PKGTOP)/bkmk/Make.include
-include $(GROUPTOP)/$(PKGTOP)/Make.include
-include $(GROUPTOP)/Make.include
-include ./Make.include
## END BKSTANDARD MAKEFILE
##################################################
