######################################################################
##
## clc makefile
##
######################################################################

SUBDIR=	fsma dict misc pq pset sio str timer xlog

TOPDIR=..
CURDIR=src

include $(TOPDIR)/Make.include
